spring:
  h2:
    console:
      enabled: true
      path: /h2

    datasource:
      url: jdbc:h2:mem:bookjeok;DB_CLOSE_DELAY=-1
      driver-class-name: org.h2.Driver
      username: sa
      password:

