spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:mem:bookjeok;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    database: h2
    show-sql: true

  devtools:
    livereload:
      enabled: false

  thymeleaf:
    mode: HTML
    cache: false
    encoding: UTF-8